spring.application.name=eureka-server

server.port=8761

# Deshabilita registro propio
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Desactivar cuando se utiliza Docker
eureka.instance.hostname: eureka-server
# Nombre del servicio en docker
# eureka.instance.prefer-ip-address: true 
# Utiliza la dirección IP en lugar del nombre de host
